force-app/main/default/objects/Portal_User__c/Portal_User__c.object-meta.xml
<CustomObject>
    <label>Portal User</label>
    <nameField>
        <label>Portal User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_User__c/fields/Is_First_Login__c.field-meta.xml
<CustomField>
    <fullName>Is_First_Login__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is First Login</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Portal_User__c/fields/Password_Hash__c.field-meta.xml
<CustomField>
    <fullName>Password_Hash__c</fullName>
    <label>Password Hash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_User__c/fields/Temporary_Password__c.field-meta.xml
<CustomField>
    <fullName>Temporary_Password__c</fullName>
    <label>Temporary Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PortalUserTriggerHandler.cls
public class PortalUserTriggerHandler {

    public static void handleBeforeInsert(List<Portal_User__c> newRecords) {
        processPasswordHashing(newRecords);
    }


    public static void handleBeforeUpdate(List<Portal_User__c> newRecords,Map<Id, Portal_User__c> oldMap) {
        processPasswordHashing(newRecords);
    }


    private static void processPasswordHashing(List<Portal_User__c> records) {

        for (Portal_User__c user : records)
        {

            if (String.isNotBlank(user.Temporary_Password__c))
            {

                user.Password_Hash__c =
                    generateHash(user.Temporary_Password__c);

                user.Temporary_Password__c = null;

                user.Is_First_Login__c = true;

            }

        }

    }


    private static String generateHash(String password) {

        return EncodingUtil.base64Encode(
            Crypto.generateDigest(
                'SHA-256',
                Blob.valueOf(password)
            )
        );

    }

}